### ISSUE TITLE
Problems with Import Call

### ISSUE THREAD

**Issue by fizzy79** [freshplanet/ANE-Flurry#23]
I'm trying to get this ANE working (after switching from the StickSports one, since it is unsupported now) but I'm having trouble when compiling. 

I'm importing with the following line:

import com.freshplanet.AirFlurry;

But I'm getting an error:

1172: Definition com.freshplanet:AirFlurry could not be found.

I've tried a few different imports but none of them seem to be working. Am I importing the package incorrectly? What is the actual import supposed to be?

Thanks!

**Comment by gameaccount** [comment]
import com.freshplanet.nativeExtensions.Flurry;

**Comment by fizzy79** [comment]
Terrific, thank you! :+1:
